<!DOCTYPE html>
<html lang="en-US">
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
    <script>
        angular.module("myApp", []).controller("myCtrl", function ($scope) 
                                               {
            // this will hold the amounts that are entered
            $scope.amounts =  [];

            //define what happens when the button is clicked
            $scope.addAmountAndTotal = function()
            {
                //alert("button clicked");
                $scope.amounts.push($scope.currentAmount);
                $scope.currentAmount = "";
                $scope.total = 0;
                for(var n = 0; n < $scope.amounts.length; n++)
                {
                    $scope.total += Number($scope.amounts[n]);
                }
                console.log($scope.amounts);
            };
            //alert("initializing");
        });
    </script>

    <body>
        <div ng-app="myApp" ng-controller="myCtrl">
            <div ng-repeat="(n, listAmount) in amounts track by n">{{listAmount}}</div>
            <form><p>Amount : <input type="text" ng-model="currentAmount"></p>
                <button type = "submit" ng-click="addAmountAndTotal()">Add</button>
            </form>
            <p>Total: {{total}}</p>
        </div>

    </body>
</html>