<!DOCTYPE html>
<html lang="en-US">
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
    <script>
        angular.module("myApp", []).controller("myCtrl", function ($scope, $http) 
                                               {
            // this will hold the amounts that are entered
            $scope.tasks =  [];
            $scope.task = {};
            //define what happens when the button is clicked
            $scope.addTask = function()
            {
                //alert("button clicked");
                $scope.tasks.push($scope.task.currentTask);
                $http.post("/tasks", $scope.task).success(function(oRc){
                    console.log(oRc);
                    $scope.task.currentTask = "";
                });
            };
            //alert("initializing");
        });
    </script>

    <body>
        <div ng-app="myApp" ng-controller="myCtrl">
            <div ng-repeat="(n, listTask) in tasks track by n">{{listTask}}</div>
            <form><p>New Task : <input type="text" ng-model="task.currentTask"></p>
                <button type = "submit" ng-click="addTask()">Add</button>
            </form>
        </div>

    </body>
</html>